### ISSUE TITLE
Conda package not working in Mac M1 

### ISSUE THREAD

**Issue by juanjo255** [CMU-SAFARI/BLEND#5]
Hello!
I was interested in using the program. I installed the program following a step-by-step process in a Mac M1:

```
mamba create -n blend-bio
mamba install -c bioconda blend-bio
blend -h 
```

and the output was:

`50665 illegal hardware instruction  blend -h`

I also tried using a environment with x86 architecture, but it produced the same error.

I hope you can help me. 

Thanks!

**Comment by canfirtina** [comment]
Hi @juanjo255,

Unfortunately, we have not tested the installation on devices running macOS regardless of their processor architecture. I am not sure if this would be supported soon.

If you have not already done it, I would suggest using a linux machine to test if the conda setup works fine. Please let me know if you still have issues with installation on a linux machine.

Thanks,
Can
